// M0 feasibility probe. Not deployable: used only with wrangler.probe.jsonc
// to exercise the OpenNext artifact plus a transactional SQLite DO, alarm and
// Queue in one local workerd process.
import { DurableObject } from 'cloudflare:workers';
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNext from '../../.open-next/worker.js';

type Env = {
  PROBE_STORE: DurableObjectNamespace<ProbeStore>;
  PROBE_QUEUE: Queue<{ id: string }>;
  SESSION_SECRET?: string;
};

function envPresence(env: Env) {
  return {
    processEnvSecret: typeof process !== 'undefined' && typeof process.env?.SESSION_SECRET === 'string' && process.env.SESSION_SECRET.length > 0,
    bindingSecret: typeof env.SESSION_SECRET === 'string' && env.SESSION_SECRET.length > 0,
  };
}

export class ProbeStore extends DurableObject<Env> {
  sql: SqlStorage;
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.sql = ctx.storage.sql;
    ctx.blockConcurrencyWhile(async () => {
      this.sql.exec(`CREATE TABLE IF NOT EXISTS rows (id TEXT PRIMARY KEY, note TEXT, at INTEGER)`);
    });
  }
  private rows() {
    return this.sql.exec<{ id: string; note: string }>(`SELECT id, note FROM rows ORDER BY at, id`).toArray();
  }
  async snapshot() {
    return { rows: this.rows(), alarm: await this.ctx.storage.getAlarm() };
  }
  async reset() {
    this.sql.exec(`DELETE FROM rows`);
    await this.ctx.storage.deleteAlarm();
    return this.snapshot();
  }
  async rollbackAfterSql() {
    let error = null;
    try {
      await this.ctx.storage.transaction(async () => {
        this.sql.exec(`INSERT INTO rows VALUES (?, ?, ?)`, 'rollback-1', 'should-not-exist', Date.now());
        await this.ctx.storage.setAlarm(Date.now() + 600_000);
        throw new Error('injected-after-alarm');
      });
    } catch (e) {
      error = (e as Error).message;
    }
    return { error, ...(await this.snapshot()) };
  }
  async alarmRegistrationFails() {
    let error = null;
    try {
      await this.ctx.storage.transaction(async () => {
        this.sql.exec(`INSERT INTO rows VALUES (?, ?, ?)`, 'alarmfail-1', 'should-not-exist', Date.now());
        await this.ctx.storage.setAlarm(Number.NaN);
      });
    } catch (e) {
      error = (e as Error).message.slice(0, 120);
    }
    return { error, ...(await this.snapshot()) };
  }
  async commitThenStall(id: string, dueInMs: number, stallMs: number) {
    await this.ctx.storage.transaction(async () => {
      this.sql.exec(`INSERT INTO rows VALUES (?, ?, ?)`, id, 'committed', Date.now());
      const existing = await this.ctx.storage.getAlarm();
      const due = Date.now() + dueInMs;
      if (existing === null || due < existing) await this.ctx.storage.setAlarm(due);
    });
    await new Promise((r) => setTimeout(r, stallMs));
    return this.snapshot();
  }
  async stallInsideTransaction(id: string, stallMs: number) {
    await this.ctx.storage.transaction(async () => {
      this.sql.exec(`INSERT INTO rows VALUES (?, ?, ?)`, id, 'uncommitted', Date.now());
      await this.ctx.storage.setAlarm(Date.now() + 15_000);
      await new Promise((r) => setTimeout(r, stallMs));
    });
    return this.snapshot();
  }
  async competing(dueInMs: number) {
    await this.ctx.storage.transaction(async () => {
      const existing = await this.ctx.storage.getAlarm();
      const due = Date.now() + dueInMs;
      if (existing === null || due < existing) await this.ctx.storage.setAlarm(due);
    });
    return this.snapshot();
  }
  async recordDelivery(id: string, presence: unknown) {
    this.sql.exec(`INSERT OR REPLACE INTO rows VALUES (?, ?, ?)`, `delivery-${id}`, JSON.stringify(presence), Date.now());
    return this.snapshot();
  }
  async alarm() {
    const presence = envPresence(this.env);
    this.sql.exec(`INSERT OR REPLACE INTO rows VALUES (?, ?, ?)`, `alarm-${Date.now()}`, JSON.stringify(presence), Date.now());
    await this.env.PROBE_QUEUE.send({ id: `from-alarm-${Date.now()}` });
  }
}

const probeWorker = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(request.url);
    if (url.pathname.startsWith('/__probe/')) {
      const stub = env.PROBE_STORE.getByName('probe');
      const op = url.pathname.slice('/__probe/'.length);
      const q = (k: string, d: number) => Number(url.searchParams.get(k) ?? d);
      let body: unknown;
      switch (op) {
        case 'reset': body = await stub.reset(); break;
        case 'snapshot': body = await stub.snapshot(); break;
        case 'rollback': body = await stub.rollbackAfterSql(); break;
        case 'alarmfail': body = await stub.alarmRegistrationFails(); break;
        case 'commit': body = await stub.commitThenStall(url.searchParams.get('id') ?? 'c', q('due', 60_000), q('stall', 0)); break;
        case 'stall-in-tx': body = await stub.stallInsideTransaction(url.searchParams.get('id') ?? 's', q('stall', 20_000)); break;
        case 'competing': body = await stub.competing(q('due', 60_000)); break;
        case 'send': await env.PROBE_QUEUE.send({ id: url.searchParams.get('id') ?? 'x' }); body = { sent: true }; break;
        case 'presence': body = envPresence(env); break;
        default: return new Response('unknown probe', { status: 404 });
      }
      return Response.json(body);
    }
    return openNext.fetch(request, env, ctx);
  },
  async queue(batch: MessageBatch<{ id: string }>, env: Env) {
    for (const message of batch.messages) {
      await env.PROBE_STORE.getByName('probe').recordDelivery(message.body.id, envPresence(env));
      message.ack();
    }
  },
};

export default probeWorker;
