// M0 probe entrypoint (replaced by the real entrypoint in later milestones).
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNext from '../.open-next/worker.js';

export default {
  fetch(request: Request, env: unknown, ctx: unknown) {
    return openNext.fetch(request, env, ctx);
  },
};
