// M0 probe entrypoint (replaced by the real entrypoint in later milestones).
// @ts-expect-error generated by `opennextjs-cloudflare build`; no declarations
import openNext from '../.open-next/worker.js';

const worker = {
  fetch(request: Request, env: Env, ctx: ExecutionContext) {
    return openNext.fetch(request, env, ctx);
  },
};

export default worker;
