// The single deployable Worker (RT-02): OpenNext `fetch`, an independent
// Queue consumer for durable analysis, and the WorkspaceStore Durable Object.
//
// Ingress responsibilities (RT-01, RT-05, RT-07):
//  - refuse to serve unless this Worker's declared target is `cloudflare`, so
//    the backward-compatible Node default can never activate Redis here;
//  - derive the admission identity from CF-Connecting-IP only and carry it,
//    with the invocation's env, in AsyncLocalStorage (never in a header a
//    browser could forge);
//  - strip the reserved internal header namespace from incoming requests.
import { AsyncLocalStorage } from 'node:async_hooks';
// @ts-expect-error generated by `opennextjs-cloudflare build`; no declarations
import openNext from '../.open-next/worker.js';
import { cloudflareAdmissionIdentity } from '../src/lib/runtime/clientAddress';
import {
  WORKER_INVOCATION_ACCESSOR,
  WORKER_RUNTIME_MARKER,
  type WorkerInvocation,
} from '../src/lib/runtime/workerInvocation';
import { handleAnalysisBatch, type ConsumerEnv } from './analysis/consumer';

export { WorkspaceStore } from './workspace/WorkspaceStore';

type OpenNextHandler = { fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> };

const invocations = new AsyncLocalStorage<WorkerInvocation>();
const runtimeGlobals = globalThis as unknown as Record<symbol, unknown>;
runtimeGlobals[WORKER_RUNTIME_MARKER] = true;
runtimeGlobals[WORKER_INVOCATION_ACCESSOR] = () => invocations.getStore() ?? null;

const INTERNAL_HEADER_PREFIX = 'x-openinterviewer-internal-';

function withoutInternalHeaders(request: Request): Request {
  let reserved = false;
  for (const name of request.headers.keys()) {
    if (name.toLowerCase().startsWith(INTERNAL_HEADER_PREFIX)) {
      reserved = true;
      break;
    }
  }
  if (!reserved) return request;
  const headers = new Headers(request.headers);
  for (const name of [...headers.keys()]) {
    if (name.toLowerCase().startsWith(INTERNAL_HEADER_PREFIX)) headers.delete(name);
  }
  return new Request(request, { headers });
}

function misconfigured(): Response {
  return new Response(
    JSON.stringify({ error: 'This deployment is not configured for Cloudflare.', retryable: false }),
    { status: 503, headers: { 'content-type': 'application/json', 'cache-control': 'no-store' } },
  );
}

const worker = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const workerEnv = env as unknown as Record<string, unknown>;
    if (workerEnv.DEPLOYMENT_TARGET !== 'cloudflare') return misconfigured();
    const identity = cloudflareAdmissionIdentity(request.headers);
    const invocation: WorkerInvocation = { env: workerEnv, identity, source: 'fetch' };
    return invocations.run(invocation, () =>
      (openNext as OpenNextHandler).fetch(withoutInternalHeaders(request), env, ctx),
    );
  },

  async queue(batch: MessageBatch<unknown>, env: Env, ctx: ExecutionContext): Promise<void> {
    const workerEnv = env as unknown as Record<string, unknown>;
    if (workerEnv.DEPLOYMENT_TARGET !== 'cloudflare') {
      // Never acknowledge work this deployment cannot legitimately process.
      for (const message of batch.messages) message.retry();
      return;
    }
    const invocation: WorkerInvocation = { env: workerEnv, identity: null, source: 'queue' };
    await invocations.run(invocation, () =>
      handleAnalysisBatch(batch, env as unknown as ConsumerEnv, ctx),
    );
  },
};

export default worker;
