// POST /api/synthesis - Researcher-preview-only interview analysis
// Server-side only - API keys never sent to client
// Slice P: the participant never calls this route. A completed interview is
// durable the moment it saves; the analysis is a separate, server-run act
// (src/lib/interviewAnalysis.ts). This route now exists only so a researcher
// previewing a study (which never persists, save/route.ts:preview) can see a
// real reading without the participant dataset ever being touched.
// Provider/model/prompts always come from the canonical saved study loaded
// server-side; request bodies are never authoritative.

import { NextResponse } from 'next/server';
import {
  getInterviewProvider,
} from '@/lib/providers';
import {
  providerKeysFromContext,
  resolveParticipantOrPreviewContext,
  selectedStudyIdFromParticipantBody,
} from '@/lib/researcherContext';
import { loadCanonicalStudy } from '@/lib/canonicalStudy';
import { providerErrorResponse } from '@/lib/providerErrors';
import { hostedAiRateLimitResponse } from '@/lib/platformAiRateLimit';
import { validateBehavior, validateProfile, validateTranscript } from '@/lib/interviewSubmission';
import { readBoundedJsonObject } from '@/lib/requestBody';
import {
  StudyConfig,
  ParticipantProfile,
  InterviewMessage,
  BehaviorData
} from '@/types';
import { createRequestId, logRequestEvent, logRequestFailure } from '@/lib/requestLog';
import { resolveEvidenceRef } from '@/lib/evidence';

export async function POST(request: Request) {
  try {
    const parsedBody = await readBoundedJsonObject(request, 600_000);
    if (!parsedBody.ok) {
      return NextResponse.json(
        { error: parsedBody.status === 413 ? 'Synthesis request is too large.' : 'Synthesis request is malformed.' },
        { status: parsedBody.status }
      );
    }
    const body = parsedBody.value;

    const { valid, context, studyId, isAdmin, error, statusCode } =
      await resolveParticipantOrPreviewContext(request, {
        purpose: 'read',
        selectedStudyId: selectedStudyIdFromParticipantBody(body),
      });
    if (!valid || !context) {
      return NextResponse.json(
        { error: error || 'Valid participant token required' },
        { status: statusCode ?? 401 }
      );
    }

    // Interview analysis is generated by the researcher, deferred from a
    // participant's save. A participant token has no caller left here.
    if (!isAdmin) {
      return NextResponse.json(
        { error: 'Interview analysis is generated by the researcher.' },
        { status: 403 }
      );
    }

    let {
      history,
      behaviorData,
      participantProfile
    } = body as {
      history: InterviewMessage[];
      studyConfig?: StudyConfig; // Legacy display payload — never authoritative
      behaviorData: BehaviorData;
      participantProfile: ParticipantProfile | null;
    };

    // Validate required fields
    if (!history || !behaviorData) {
      return NextResponse.json(
        { error: 'Missing required fields: history, behaviorData' },
        { status: 400 }
      );
    }

    try {
      history = validateTranscript(history);
      behaviorData = validateBehavior(behaviorData);
      participantProfile = validateProfile(participantProfile);
    } catch {
      return NextResponse.json({ error: 'Interview data is malformed or exceeds allowed limits.' }, { status: 400 });
    }

    // Canonical study authority: the token's studyId wins; the body may carry
    // only a study id for authenticated admin previews.
    const canonical = await loadCanonicalStudy({
      kvClient: context.kvClient,
      tokenStudyId: studyId,
      legacyBodyStudyId: (body as { studyConfig?: StudyConfig }).studyConfig?.id,
      isAdmin,
    });
    if (!canonical.ok) {
      return canonical.response;
    }

    const platformLimited = await hostedAiRateLimitResponse(
      request,
      'synthesis',
      {
        researcherId: context.researcherId,
        participantSessionId: undefined,
      }
    );
    if (platformLimited) return platformLimited;

    let provider;
    try {
      provider = getInterviewProvider(canonical.study.config, providerKeysFromContext(context));
    } catch {
      return NextResponse.json(
        { error: 'AI provider is not configured on the server.' },
        { status: 502 }
      );
    }

    try {
      const result = await provider.synthesizeInterview(
        history,
        canonical.study.config,
        behaviorData,
        participantProfile
      );
      // Match-rate telemetry (ADR-003: counts only — never quote or turn text).
      // Telemetry must never fail the synthesis response.
      try {
        const refs = result.value.themes.flatMap(theme => theme.evidenceRefs ?? []);
        logRequestEvent({
          event: 'synthesis.evidence',
          requestId: createRequestId(request.headers.get('x-request-id')),
          route: '/api/synthesis',
          refsOffered: refs.length,
          refsLocated: refs.filter(ref => resolveEvidenceRef(ref, history).status === 'verified').length,
        });
      } catch {
        // Swallowed by design: the matcher never throws by contract, but a
        // telemetry failure must never cost the preview its reading.
      }
      return NextResponse.json(result.value);
    } catch (providerError) {
      return providerErrorResponse(providerError);
    }
  } catch (error) {
    logRequestFailure({
      event: 'route.failure',
      route: '/api/synthesis',
      method: 'POST',
      status: 500,
      requestId: createRequestId(request.headers.get('x-request-id')),
    }, error);
    return NextResponse.json(
      { error: 'Failed to synthesize interview' },
      { status: 500 }
    );
  }
}
